### ISSUE TITLE
https://node-red-google-home.herokuapp.com/ not working

### ISSUE THREAD

**Issue by wolfjank** [andrei-tatar/nora-firebase-common#1]
Hi Andrei, 

i really like the Nora / Google integration.

In the last month i very often had the "Nora is not available" problem. (my wifes name is Nora -> so first of all i was very confused about that message :-)) 

I tried to fix it by relinking the google account to Nora in the google home settings and at the website: [https://node-red-google-home.herokuapp.com] But this is not working. After logging in with my google- or github-account always the login-mask appears.

Can you please help me? 

Kind regards
Wolfgang

**Comment by andrei-tatar** [comment]
Hi, unfortunately nora can't handle the big rise in the number of users.
I'm working on a new version that will be firebase based that will scale out much more easier.

This repository is actually part of the new version

**Comment by wolfjank** [comment]
Thanks for your fast answer. These are good  news!

Do you have a plan about the releasing already? Do i have to wait for a long period of time?

Thank you very much for your efforts! :-)

**Comment by andrei-tatar** [comment]
I'm working on it. It will probably be a few weeks before the first beta.

**Comment by andrei-tatar** [comment]
https://smart-nora.eu/ is now live and connectable from Google Home app. Will close this issue.
