### ISSUE TITLE
Include Google intent in msg.payload

### ISSUE THREAD

**Issue by Toby-Mills** [andrei-tatar/nora-firebase-common#8]
@andrei-tatar I'm writing a node-red flow for my sprinkler system. Because it uses a mix of traits (start/stop & timer), it can be difficult from the updateState to figure out what the original Intent from Google Home was. It would be useful to explicitly know if the user said 'start', 'stop', or 'set a timer', without having to figure it out by comparing states.

Do you think it would be feasible to (maybe optionally) include the original intent command and parameters along with the state object?

**Comment by andrei-tatar** [comment]
@Toby-Mills probably the easiest way is to enable async command execution for the sprinkler device. https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/nodes/async.md

You would get the original command from Google Home and can decide in the flow how to handle it and update the state if necessary.

Otherwise, including the original execute intent might makes things a bit tricky and confusing.

**Comment by Toby-Mills** [comment]
@andrei-tatar this seems like a good approach. I've tried adding `asyncCommandExecution: !!config.asyncCmd,` to the Device Config for the node, but I immediately get an error `"RangeError: Invalid array length"` when the flow starts up.
Is there anything else I need to change to support the async pattern?

**Comment by andrei-tatar** [comment]
@Toby-Mills it's most probable because async command nodes need 2 outputs (1 for state, 1 for async commands). Check the other nodes html file, where the number of outputs on a node is set to 2 when `asyncCmd` is set to `true`.

**Comment by Toby-Mills** [comment]
thanks @andrei-tatar  I have set outputs to 2, and provided an array of 2 values for outputLabels, but the same error remains. I also notice in the console, each time I deploy the flows it appears to increment the number of nora devices reported as synced (as though the invalid device is not being removed from the nora service during the syncing process).
Is there a way I can clear all devices on the Group?

**Comment by andrei-tatar** [comment]
@Toby-Mills can you share your branch? I can have a look

**Comment by Toby-Mills** [comment]
@andrei-tatar have a look at https://github.com/Toby-Mills/node-red-contrib-smartnora/tree/feature/sprinkler-async

**Comment by andrei-tatar** [comment]
@Toby-Mills found the issue. The problem is that `outputs` needs to be a node config value as well. Will push the fix soon directly on my repo. Also want to push a feature to SSO in node-red to no longer enter the password.

**Comment by andrei-tatar** [comment]
@Toby-Mills pushed and published package version `1.11.0`. Can you please check if it's working for you?

**Comment by Toby-Mills** [comment]
That has sorted it out! Thanks for your help @andrei-tatar !
